import { StyleSheet } from "react-native";
import { COLORS, SIZESFONT } from "../constants/Theme";
export const globalStyles = StyleSheet.create({

    container: {
        flex: 1,
        padding: 10,
        backgroundColor: '#202124'
  },
  containerCenter: {
      flex: 1,
      padding: 10,
    backgroundColor: '#202124',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  cardHome: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      backgroundColor: '#1B1C1E',
      borderRadius: 6,
      height: 200,
      borderColor: '#37393A',
      borderWidth: 1,
      paddingTop: 10,
      paddingBottom: 10,
      paddingRight: 10,
  },
  buttonFicha: {
    flex: 1,
    width: '100%',
    height: 50,
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    borderRadius: 8,
  },
  buttonRegister: {
      position: 'absolute',
      bottom: 50, /* Aqui es 20 tambien, con 50 se puede dar click al boton */
      left: 20,
      right: 20,
      backgroundColor: '#37393A',
  },
  buttonSave: {
      height: 50,
      backgroundColor: '#37393A',
      borderRadius: 8,
      paddingHorizontal: 15,
      width: '100%',
      justifyContent: 'center', // Centra verticalmente
      alignItems: 'center' // Centra horizontalmente
  },
  buttonText: {
      color: '#F1F3F4',
      fontSize: 15,
      fontWeight: 'bold',
      textAlign: 'center',
  },
  // FabMenu
  fabmenu: {
    height: 80,
    width: 80,
    backgroundColor: COLORS.secundaryButton,
    position: 'absolute',
    bottom: 16,
    right: 16,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  fabclose: {
    height: 56,
    width: 56,
    backgroundColor: COLORS.black,
    position: 'absolute',
    bottom: 40,
    right: 16,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  menuitem: {
    height: 56,
    position: 'absolute',
    right: 16,
    paddingLeft: 24,
    paddingRight: 24,
    backgroundColor: COLORS.secundaryButton,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  globotext: {
    position: 'absolute',
    bottom: 46,
    right: 105,
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  // UserPet
  cardUserPet: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#1B1C1E',
    borderRadius: 6,
    width: 203,
    borderColor: '#37393A',
    borderWidth: 1,
    paddingBottom: 20,
  },
  textpH1: {
    color: COLORS.font,
    fontSize: SIZESFONT.h1,
    marginTop: 8,
  },
  textpH2: {
    color: COLORS.font,
    fontSize: SIZESFONT.h2,
    marginTop: 0,
  },
  textp: {
    color: COLORS.font,
    fontSize: SIZESFONT.paragraph,
    marginTop: 0,
  },
  cardH1: {
    color: COLORS.font,
    fontSize: SIZESFONT.h1,
    marginTop: 0,
  },
  cardPet: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: '#1B1C1E',
    borderRadius: 6,
    width: '100%',
    borderColor: '#37393A',
    borderWidth: 1,
    paddingBottom: 20,
    paddingTop: 20,
    paddingLeft:20,
    marginTop: 30,
  },
  cardOwner: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: '#1B1C1E',
    borderRadius: 6,
    width: '100%',
    borderColor: '#37393A',
    borderWidth: 1,
    paddingBottom: 20,
    paddingTop: 10,
    paddingLeft:20,
    marginTop: 30,
  },
});
